Fix bot start script
osscameroon/tg-gamebot pull request #24
Opened 2022-04-05 18:04 UTC by elroykanye

fixes #23

Changes coming into this repo from this branch include:
 - An additional `launch` command to the `bot.sh` script
 - An alternative powershell shell script for windows
 - changes to gitignore and API key loader

2022-04-06 04:01 UTC, andrew21-mch approved these changes
Looks good but still have difficulty understanding it though

2022-04-06 04:11 UTC, elroykanye commented
Oh yes, I will have to explain that to you this morning.

Let's chat this later in the morning in the telegram group so @Mankavelda can follow

2022-04-08 17:27 UTC, elhmn requested changes
This seems a little too complicated and might be bug prone in the future.

Can you try to use a Makefile instead, you can find some documentation on how to setup one.

Here is an example of Makefile we made for some python projects we worked on, you can maybe use it as inspiration.

https://github.com/osscameroon/global-github-actions/blob/main/.github/workflows/social_media_message_scheduler/Makefile

2022-04-08 17:30 UTC, elhmn commented on src/app/utils.py
> +key_dir = "./.secrets/API.csv"
To store secrets, I would recommend you use a `.env` file here is an (example of file)[https://github.com/osscameroon/global-github-actions/blob/main/.github/workflows/social_media_message_scheduler/.example-secret-env] we already used in the past .

You can have a look at the social_media_message_scheduler folder to check how this file is used.

2022-04-15 20:05 UTC, elhmn commented on Makefile
> +# ###########################################################
This header is not required and should be removed.

2022-04-15 20:05 UTC, elhmn commented on Makefile
> +# ###########################################################
Let's remove this comments

2022-04-15 20:05 UTC, elhmn commented on Makefile
> +.PHONY: launch
Generally, the target to run the application is set to `run` instead of `launch` can we follow that pattern in this makefile as well?

2022-04-15 20:20 UTC, elroykanye commented on Makefile
> +.PHONY: launch
Oh yes!

2022-04-15 20:21 UTC, elroykanye commented on Makefile
> +# ###########################################################
Noted! Thanks 😁

2022-04-19 19:47 UTC, elhmn requested changes

2022-04-19 19:47 UTC, elhmn commented on Makefile
> +	@echo "Launching bot..."
```suggestion
	@echo "Running bot..."
```

2022-04-19 19:47 UTC, elhmn commented on Makefile
> +	@echo "Installing dependencies"
If you are using `...`, I would suggest that you use it everywhere to make it more consistent across the file.

2022-04-19 19:47 UTC, elhmn commented on Makefile
> +	@echo "  clean: clean the bot"
what does `clean the bot` mean ? Could we be more explicit about what it actually does ?

2022-04-19 19:47 UTC, elhmn commented on src/app/utils.py
> +key_dir = "./.secrets/API.csv"
I think that was already resolved somewhere else, maybe if you rebase this PR on top of main, this changes might disapear

2022-04-19 20:04 UTC, elroykanye commented on Makefile
> +	@echo "Installing dependencies"
Okay, that is true! :)

2022-04-19 20:05 UTC, elroykanye commented on Makefile
> +	@echo "Launching bot..."
Oh! Thanks for this

2022-04-19 20:06 UTC, elroykanye commented on Makefile
> +	@echo "  clean: clean the bot"
There are some cache files generated during testing. When we finally understand how to write tests in python and for this bot, we may need it clear that folder. I just added in case. If it is not really necessary, I can remove :)

2022-04-19 20:19 UTC, andrew21-mch commented
Hi @elroykanye i find conflict in this pull request, check that out

2022-04-19 20:22 UTC, elhmn commented on Makefile
> +	@echo "  clean: clean the bot"
I understand now, alright leave it as is for now 👌

2022-04-19 20:29 UTC, elroykanye commented on src/app/utils.py
> +key_dir = "./.secrets/API.csv"
I just merged the updates from main into this because it caused a conflict and it adjusted that. Is that okay?

2022-04-19 20:30 UTC, elroykanye commented on Makefile
> +	@echo "Installing dependencies"
I have updated with the recent commits

2022-04-21 06:32 UTC, elhmn approved these changes
Great work 🥇

2022-04-21 07:12 UTC, merged