Selection menu
osscameroon/tg-gamebot pull request #30
Opened 2022-04-15 00:24 UTC by andrew21-mch

fixes #9

Changes coming into this repo from this branch include:
 - Updated the bot.py with a function for keyboard menu

2022-04-15 00:25 UTC, andrew21-mch commented
![job](https://user-images.githubusercontent.com/58951422/163496857-814d2980-3c12-4c9e-9e20-3e7a00b731d7.png)
heres is the look

2022-04-15 00:25 UTC, andrew21-mch commented
hi @elroykanye this is what i have been able to do so far, i think we can build from here

2022-04-15 00:34 UTC, elroykanye commented
Thanks, I will connect to this end this morning

2022-04-15 00:38 UTC, andrew21-mch commented
> Thanks, I will connect to this end this morning

ok then good night

2022-04-15 12:19 UTC, andrew21-mch reviewed
I am good with this 
Will have to pull it 

@elhmn please you can check this out

2022-04-15 12:20 UTC, elroykanye commented
it will not run 😅

2022-04-15 12:22 UTC, andrew21-mch commented
> it will not run 😅

Oh haha
We keep working then

2022-04-15 12:30 UTC, elroykanye commented
It will run now. The is no problem. Apparently, I renamed every `start` in my project and it affected even the libraries I had.
I just reinit the venv

2022-04-15 12:36 UTC, elroykanye commented
Here is the most recent selection menu

![Screenshot_20220415-133530](https://user-images.githubusercontent.com/68631069/163571405-d284b5bc-5023-4857-bfa6-3474e6e451cf.png)

2022-04-15 12:42 UTC, elroykanye commented
We'll have to remove this from draft before calling @elhmn to review. 
Let's resolve something in the discussions.

2022-04-15 12:46 UTC, andrew21-mch commented
Ok

On Fri, Apr 15, 2022, 1:43 PM Elroy Kanye ***@***.***> wrote:

> We'll have to remove this from draft before calling @elhmn
> <https://github.com/elhmn> to review.
> Let's resolve something in the discussions.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/osscameroon/tg-gamebot/pull/30#issuecomment-1100082864>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOBYN7SI6MRLUC3N36RYVU3VFFP5NANCNFSM5TPHJDWQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-04-16 05:52 UTC, andrew21-mch commented
Guess i did something incorrect, still worked on the help section and pushed to this branch instead, anyway to fix that @elroykanye

2022-04-16 08:17 UTC, elroykanye commented
It is fine. That is part of this from the discussion we had.

2022-04-18 18:23 UTC, Mankavelda commented
looks nice

2022-04-19 19:58 UTC, elhmn requested changes
Nice work, I left comments regarding how you named your functions and documented the code in general

2022-04-19 19:58 UTC, elhmn commented on src/app/bot.py
> +def oss_bot_help(update: Update, context: CallbackContext):
I find the `help_command` name for this function more appropriate. When naming a function it should be easier for the maintainers (someone reading the code) to figure out what it does simply by reading the name of the function.

2022-04-19 19:58 UTC, elhmn commented on src/app/bot.py
> +def oss_bot_menu(update: Update, context: CallbackContext) -> None:
```suggestion
def resume_command(update: Update, context: CallbackContext) -> None:
```

2022-04-19 19:58 UTC, elhmn commented on src/app/bot.py
> +def oss_bot_help(update: Update, context: CallbackContext):
```suggestion
def help_command(update: Update, context: CallbackContext):
```

2022-04-19 19:58 UTC, elhmn commented on src/app/bot.py
> +def oss_bot_resume(update: Update, context: CallbackContext) -> None:
```suggestion
def resume_command(update: Update, context: CallbackContext) -> None:
```

2022-04-19 19:58 UTC, elhmn commented on src/app/bot.py
> +def oss_bot_pause(update: Update, context: CallbackContext) -> None:
```suggestion
def pause_command(update: Update, context: CallbackContext) -> None:
```

2022-04-19 19:58 UTC, elhmn commented on src/app/bot.py
> +def oss_bot_schedule(update: Update, context: CallbackContext) -> None:
```suggestion
def schedule_command(update: Update, context: CallbackContext) -> None:
```

2022-04-19 19:58 UTC, elhmn commented on src/app/bot.py
> +def oss_bot_stop(update: Update, context: CallbackContext) -> None:
```suggestion
def stop_command(update: Update, context: CallbackContext) -> None:
```

2022-04-19 19:58 UTC, elhmn commented on src/app/bot.py
> +def oss_bot_leaderboard(update: Update, context: CallbackContext) -> None:
```suggestion
def leaderboard_command(update: Update, context: CallbackContext) -> None:
```

2022-04-19 19:58 UTC, elhmn commented on src/app/bot.py
> +def oss_bot_games(update: Update, context: CallbackContext):
```suggestion
def list_games_command(update: Update, context: CallbackContext):
```

2022-04-19 19:58 UTC, elhmn commented on src/app/bot.py
> +def oss_bot_about(update: Update, context: CallbackContext) -> None:
```suggestion
def about_command(update: Update, context: CallbackContext) -> None:
```

2022-04-19 19:58 UTC, elhmn commented on src/app/bot.py
> +def oss_bot_start(update: Update, context: CallbackContext) -> None:
```suggestion
def start_command(update: Update, context: CallbackContext) -> None:
```

2022-04-19 19:58 UTC, elhmn commented on src/app/bot.py
>  # show available games
I will recommend that you use docstrings to comment your functions.

You can have a look on this [link](https://www.programiz.com/python-programming/docstrings#:~:text=As%20mentioned%20above%2C%20Python%20docstrings,the%20__doc__%20attribute.) or search more information on the web on how to correctly comment python code

2022-04-19 20:03 UTC, andrew21-mch commented on src/app/bot.py
>  # show available games
Alright Boris
we will work on that

2022-04-19 20:04 UTC, andrew21-mch commented on src/app/bot.py
>  # show available games
@Mankavelda Will you like to work on this ?

2022-04-19 20:09 UTC, elroykanye commented on src/app/bot.py
> +def oss_bot_help(update: Update, context: CallbackContext):
Okay @elhmn , will do just this

2022-04-19 20:11 UTC, elroykanye commented on src/app/bot.py
>  # show available games
I think @andrew21-mch and I should work on this while @Mankavelda adjusts the changes requested for the function names.

2022-04-19 20:14 UTC, andrew21-mch commented on src/app/bot.py
>  # show available games
ok @elroykanye

2022-04-19 20:24 UTC, elhmn commented on src/app/bot.py
>  # show available games
Wait are you all going to work on the same pull request ?

Don't you think it is faster if one person (the author of the PR) sort it out himself ?

2022-04-19 20:34 UTC, andrew21-mch commented on src/app/bot.py
>  # show available games
Its cool, let me take on that since i started

2022-04-19 20:35 UTC, elroykanye commented on src/app/bot.py
>  # show available games
We are actually trying to get @Mankavelda involved and participate more 😅 I actually feel off about more than 2 people on  the same pr but I think we will go another way

2022-04-19 21:02 UTC, andrew21-mch commented
Hi @elhmn I just did some changes now, is this okay now ?

2022-04-21 06:39 UTC, elhmn approved these changes
It looks way better, I left a comment about keeping the `requirements.txt` up to date.

2022-04-21 06:39 UTC, elhmn commented on src/app/bot.py
>  from telegram.update import Update
is these dependencies `[django, and telegram]` in the `requirements.txt` file ? You can run `python -m pip freeze > requirements.txt` to be sure

2022-04-21 06:40 UTC, elhmn commented on src/app/bot.py
>  # show available games
The best way to have @Mankavelda involved is to assign her to a separate task.

2022-04-21 07:24 UTC, elroykanye commented on src/app/bot.py
>  from telegram.update import Update
Updated master and merged into this to bring the requirements generated from the other PR. 
`django` was a mistake I think. :-|

2022-04-21 07:36 UTC, merged

2022-04-21 07:36 UTC, elroykanye approved these changes